---
version: '3'
services:
  daemon:
    build: .
    ports:
    - 127.0.0.1:8080:8080
  worker-alpine:
    build:
      context: .
      dockerfile: worker/Dockerfile.alpine
    environment:
    - REBUILDER_ADDR=http://daemon:8080
  worker-archlinux:
    build:
      context: .
      dockerfile: worker/Dockerfile.archlinux
    environment:
    - REBUILDER_ADDR=http://daemon:8080
  worker-debian:
    build:
      context: .
      dockerfile: worker/Dockerfile.debian
    environment:
    - REBUILDER_ADDR=http://daemon:8080
