[package]
name = "rebuilderd"
version = "0.1.0"
description = "rebuilderd - independent build verification daemon"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/rebuilderd"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rebuilderd-common = { version="0.1.0", path="../common" }
structopt = "0.3"
env_logger = "0.7"
actix-rt = "1.0.0"
actix-web = "2.0.0"
diesel = { version = "^1.1.0", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = { version = "1.3.0", features = ["sqlite"] }
chrono = { version = "0.4", features=["serde"] }
dotenv = "0.15"
serde = { version="1.0", features=["derive"] }
rand = "0.7.3"
dirs = "2.0.2"

# https://crates.io/crates/deb-version
