[package]
name = "rebuilderd"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rebuilderd-common = { path="../common" }
structopt = "0.3"
env_logger = "0.7"
actix-web = "2.0.0-alpha.1"
diesel = { version = "^1.1.0", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = { version = "1.3.0", features = ["sqlite"] }
chrono = { version = "0.4", features=["serde"] }
dotenv = "0.10"
serde = { version="1.0", features=["derive"] }

# https://crates.io/crates/deb-version
