[package]
name = "rebuilderd-common"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
log = "0.4"
serde = { version="1.0", features=["derive"] }
strum = "0.16.0"
strum_macros = "0.16.0"
tokio = "0.2.0-alpha.6"
reqwest = { version="0.10.0-alpha.2", features=["json"] }
chrono = { version = "0.4", features=["serde"] }
colored = "1"
