[package]
name = "rebuilderd-common"
version = "0.1.0"
description = "rebuilderd - common code"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/rebuilderd"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
log = "0.4"
serde = { version="1.0", features=["derive"] }
strum = "0.18"
strum_macros = "0.18"
reqwest = { version="0.10", features=["blocking", "json"] }
chrono = { version = "0.4", features=["serde"] }
colored = "1"
dirs = "2.0.2"
toml = "0.5.6"
