[package]
name = "rebuilderd-worker"
version = "0.4.0"
description = "rebuilderd - rebuild worker"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/rebuilderd"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rebuilderd-common = { version="=0.4.0", path="../common" }
structopt = "0.3"
env_logger = "0.7"
sodiumoxide = { version="0.2.5", features=["use-pkg-config"] }
base64 = "0.10"
toml = "0.5.6"
serde = { version="1.0", features=["derive"] }
reqwest = "0.10.4"
tempfile = "3.1.0"
url = "2.1.1"
