[package]
name = "rebuildctl"
version = "0.3.1"
description = "rebuilderd - rebuildctl client"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/rebuilderd"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rebuilderd-common = { version="=0.3.1", path="../common" }
structopt = "0.3"
env_logger = "0.7"
reqwest = { version="0.10.0", features=["json"] }
chrono = { version = "0.4", features=["serde"] }
rust-lzma = "0.5.1"
tar = "0.4"
flate2 = "1.0"
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"
colored = "1"
toml = "0.5.6"
dirs = "2.0.2"
glob = "0.3.0"
nom = "5.1.1"
