[package]
name = "rebuildctl"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rebuilderd-common = { path="../common" }
structopt = "0.3"
env_logger = "0.7"
tokio = { version="0.2", features=["macros"] }
reqwest = { version="0.10.0", features=["json"] }
chrono = { version = "0.4", features=["serde"] }
rust-lzma = "0.5.1"
tar = "0.4"
flate2 = "1.0"
serde_json = "1.0"
colored = "1"
